gpu_id: '0'
log_wandb: False

hidden_size: 64                 # (int) Number of features in the hidden state. 
dropout_prob: 0.2               # (float) Dropout rate.
loss_type: 'CE'                 # (str) Type of loss function. Range in ['BPR', 'CE'].

# dataset settings
dataset: amazon-video-games
MAX_ITEM_LIST_LENGTH: 50 
user_inter_num_interval: "[5,inf)"
item_inter_num_interval: "[5,inf)"

# dataset: gowalla
# MAX_ITEM_LIST_LENGTH: 100
# user_inter_num_interval: "[20,inf)"
# item_inter_num_interval: "[5,inf)"

# dataset: Twitch-100k
# MAX_ITEM_LIST_LENGTH: 70
# user_inter_num_interval: "[15,inf)"
# item_inter_num_interval: "[5,inf)"


split_ratio: [0.3, 0.2, 0.5]    # train/valid/test split ratio
eval_setting: full              # no use of leave-one-out

USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
load_col:
    inter: [user_id, item_id, timestamp]

# training settings
epochs: 300
train_batch_size: 2048
learner: adam
learning_rate: 0.001
eval_step: 1
stopping_step: 5
train_neg_sample_args: ~

# evalution settings
metrics: ['Hit', 'NDCG']
valid_metric: NDCG@10
eval_batch_size: 4096
weight_decay: 0.0
topk: [10, 50]